services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=auth
      - POSTGRES_PASSWORD=postgres
    volumes:
      - store_database_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  keygen:
    build: ./Keygen
    container_name: keygen_c
    volumes:
      - secrets:/secrets
    restart: no

  server:
    build: ./Server
    container_name: auth_server_c
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - secrets:/app/secrets
    depends_on:
      - database
      - keygen
    restart: unless-stopped
      
volumes:
  store_database_data:
  secrets:


